# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9073b3f00f2522c06fd29e7476a4c93a5f6343c734d6910e52cda9cfb41dae1dae5ef167f65b9248317aacfc66d491affa82a7b60493cd2d3a2b68b5acc1e71

test:
  secret_key_base: 68e5fe8ce638010d7500f9ad9c7099db6f69e7c6b6507abee97d6347039256d74a9241f880c3bdb7888158082dc6f872fe8bfcb7e392e618a5ebc89f90614737

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
